#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/honvidan/fvm/versions/1.22.6"
export "FLUTTER_APPLICATION_PATH=/Users/honvidan/GitHub/christian_picker_image/example"
export "FLUTTER_TARGET=/Users/honvidan/GitHub/christian_picker_image/example/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/honvidan/fvm/versions/1.22.6/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=0.1.11"
export "FLUTTER_BUILD_NUMBER=0.1.11"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
